name: Register Flow using Github Storage 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: prefecthq/prefect:latest
    env: 
      KEY: ${{ secrets.PREFECT_API_KEY}}
      PROJECT_NAME: 'testing'
    steps:
    - uses: actions/checkout@v2
    - uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt
    - name: Authenticate to Prefect dependencies
      run: prefect auth login -k $KEY
    - name: Register flow
      run: prefect register --project $PROJECT_NAME -p flows/flow_test.py